[package]
name = "tsuki"
version = "0.1.0"
authors = ["Sverre Johann Bjørke <sverrejb@gmail.com>"]
edition = "2018"

[dependencies]
rocket = "0.4.0"

[profile.release]
panic = "abort"
lto = true
codegen-units = 1
incremental = false
opt-level = "z"